language: node_js
sudo: required
node_js: 12.16.1
services:
    - docker
    - mongodb
before_deploy:
    - npm install
    - npm run build
    - npm run test
deploy:
    provider: heroku
    skip_cleanup: true
    api_key:
        secure: R3LPOa2LEukGYe6ddQPjPBJUIt05OW2RDv/ndFM43KdKK/7U22KjmmHztg6xQ5zdacvvzn+AntpPATg1n1dVQ6MWRVQYPkJwSO3B4pUDZw0aMd589NrQ8y9uY3u3M+lvVL20afZgc/pdY0NwoHE2q6MXyjb+z5RUB/+fKgH9g6/0xI+kCKI9VDtagq/Mc7xJrPS2vAMj59OwHaIC0BrNJ6BctXqK8YtrWQiccPScWHN7Ttq1v3ywQaKMOt/Jkj2sOK5oQwgRa5B5ZGrkHOq0AcaUGr9zqb5H3I9VmVDDxSHZ3JAApzHEMxccQs0CtAIWSnZIxmWEtESdXuyFC0RWShu504Lk3J0z6gF7wtIzgZtdnZjleNDUcWERcXolQ5WRrsUUABjKer6Plq+v7ccOe7lhhHAinXVs16P0LJWQgMeyUpM8G4aVzgl0IEutPGM21SjJYlOFs7A+41RRAyAqafhBQtjP/odTqcbr44Q3x8dO7ZFRgFgmhgNsvwLebIDoC6eltMWv9eowLg8l4yAI2AGcLsunvFqAA0DrBMqsJPPTuCWzXXNP4w+DBsGvJIVB1SZNX9uaRhA2R1buGaqtKB08SxMaGVt0JsL3rSqEqh65VycuEnmwn7repa1o04e+TBlr1ofN4ToKq3vvQEmq4oG1U6MmaisFcHehRQLKcPI=
    app: stancu-mihai
    on:
        repo: stancu-mihai/FMI-DiplomaProject
        branch: master
